### ISSUE TITLE
Broken Import

### ISSUE THREAD

**Issue by wms2537** [libp2p/go-libp2p-webrtc-direct#53]
Error when running `go get github.com/libp2p/go-libp2p-webrtc-direct`

go version go1.18 linux/amd64
```
soh@soh-MS-7B46:~/go_dev/libp2p_test/publisher$ go get github.com/libp2p/go-libp2p-webrtc-direct
github.com/libp2p/go-libp2p-webrtc-direct imports
        github.com/libp2p/go-libp2p-core/mux: cannot find module providing package github.com/libp2p/go-libp2p-core/mux
```

It seems that `github.com/libp2p/go-libp2p-core` has moved to `github.com/libp2p/go-libp2p/core` and `github.com/libp2p/go-libp2p-core/mux` has migrated to `github.com/libp2p/go-libp2p/core/network`.

**Comment by p-shahi** [comment]
We very likely won't update this repo since we're implementing a better WebRTC solution here: https://github.com/libp2p/go-libp2p/pull/1655

And yes the modules have moved, go-libp2p is now officially a monorepo now since: https://github.com/libp2p/go-libp2p/releases/tag/v0.22.0

For now I'll close this issue and see about archving/deprecating this repo
